apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: app-otel
spec:
  containers:
    - name: debug-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: varlog
          mountPath: /var/log/pods
          readOnly: true
  volumes:
    - name: varlog
      hostPath:
        path: /var/log/pods
        type: DirectoryOrCreate
