apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-otel
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: app-otel
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: app-otel
    server: https://kubernetes.default.svc
  project: app-otel
  syncPolicy:
    automated: {}

  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: v0.93.3
    helm:
      values: |-
        fullnameOverride: app-otel
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
        
        # Ajout des volumeMounts et volumes sous la clé "extraVolumeMounts" et "extraVolumes"
        extraVolumeMounts:
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
        
        extraVolumes:
          - name: varlogpods
            hostPath:
              path: /var/log/pods
              type: Directory
        
        config:
          processors:
            resourcedetection:
              detectors: [env, system]
            cumulativetodelta:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: "0.0.0.0:4317"
                http:
                  endpoint: "0.0.0.0:4318"
            filelog:
              include: [ /var/log/pods/app-mimir_app-mimir-nginx-6c8d999fb8-xgsbh_27ab3533-13e2-46a2-a056-8f50c0467dd0/nginx/0.log ]
              start_at: beginning
        
          exporters:
            loki:
              endpoint: "http://172.20.104.10:3100/loki/api/v1/push"
            prometheusremotewrite:
              endpoint: http://172.20.146.37:8080/api/v1/push
              headers:
                X-Scope-OrgID: "neosoft"
            logging:
              loglevel: debug
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [logging]
              metrics:
                receivers: [otlp]
                processors: [cumulativetodelta, batch, resourcedetection]
                exporters: [logging,prometheusremotewrite]
              logs:
                receivers: [filelog]
                processors: [batch]
                exporters: [loki]