apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-grafana
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: app-grafana
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: app-grafana
    server: https://kubernetes.default.svc
  project: app-grafana
  syncPolicy:
    automated: {}
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: v8.0.2
    helm:
      values: |-
        image:
          tag: 10.4.4
        service:
          enabled: true
          type: LoadBalancer
          port: 80
          targetPort: 3000
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        persistence:
          type: pvc
          enabled: true
          storageClassName: nfs-csi
          accessModes:
            - ReadWriteOnce
          size: 100Gi
        admin:
          existingSecret: grafana-credentials
          userKey: admin-user
          passwordKey: admin-password
        grafana.ini:
          server:
            domain: ""
            root_url: /
          smtp:
            enabled: true
            host: smtp.romain-guillemot.dev:587
            user: neosofthackathon2024super@romain-guillemot.dev
            password: SDQ5Fd6*ez-f5fs56vsdv3dqs
            skip_verify: true
            from_address: neosofthackathon2024super@romain-guillemot.dev
            from_name: Grafana
        sidecar:
          dashboards:
            searchNamespace: ALL
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Mimir
              type: prometheus
              url: http://172.20.170.61:80/prometheus
              access: proxy
              isDefault: true
              jsonData:
                httpHeaderName1: "X-Scope-OrgID"
              secureJsonData:
                httpHeaderValue1: "neosoft"
            - name: Loki
              type: loki
              url: http://app-loki-query-frontend.app-loki:3100
              access: proxy
              isDefault: false
            - name: Tempo
              type: tempo
              url: http://app-tempo-query-frontend.app-tempo:3100
              access: proxy
              isDefault: false