apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-otel
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: app-otel
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: app-otel
    server: https://kubernetes.default.svc
  project: app-otel
  syncPolicy:
    automated: {}
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: v0.93.3
    helm:
      values: |-
        fullnameOverride: app-otel
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
        config:
          receivers:
            otlp:
              protocols:
                grpc: {}
                http: {}
          processors:
            batch:
              timeout: 5s
            resource:
              attributes:
                - action: insert
                  key: job
                  value: app-otel
          exporters:
            loki:
              endpoint: "http://172.20.187.36:80/loki/api/v1/push"
              format: json
          service:
            pipelines:
              logs:
                receivers: [otlp]
                processors: [batch, resource]
                exporters: [loki]
