apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-apps
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: infra-argocd
    server: https://kubernetes.default.svc
  project: argocd-apps
  syncPolicy:
    automated: {}
  source:
    chart: infra-apps
    repoURL: https://charts.adfinis.com
    targetRevision: 0.185.0
    helm:
      values: |-
        fullnameOverride: app
        ingressNginx:
          enabled: false # Désactiver l'ingress nginx car on va utiliser un LoadBalancer
        argocd:
          enabled: true
          project: infra-argocd
          fullNameOverride: infra-argocd
          destination:
            server: https://kubernetes.default.svc
            namespace: infra-argocd
          values:
            createAggregateRoles: true
            controller:
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  cpu: 1
                  memory: 2Gi
            repoServer:
              resources:
                requests:
                  cpu: 10m
                  memory: 256Mi
                limits:
                  cpu: 1
                  memory: 4Gi
            applicationSet:
              enabled: true
            notifications:
              enabled: false
            dex:
              enabled: true
              metrics:
                enabled: true
                serviceMonitor:
                  enabled: true
            server:
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 1Gi
              config:
                admin.enabled: "true"
                users.anonymous.enabled: "false"
                statusbadge.enabled: "false"
                resource.exclusions: |
                  - apiGroups:
                    - "velero.io"
                    kinds:
                    - "Backup"
                    clusters:
                    - "*"
              staticAssets:
                enabled: true
              service:
                type: LoadBalancer
                annotations:
                  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
                ports:
                  - name: http
                    port: 80
                    targetPort: 8080
                  - name: https
                    port: 443
                    targetPort: 8080
            redis:
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi