apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-nfs
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-nfs
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-storage
  syncPolicy:
    automated: {}
  source:
    chart: csi-driver-nfs
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: 4.5.0